### ISSUE TITLE
Tutorial how to run a script with pop up

### ISSUE THREAD

**Issue by AlexD10S** [r0gue-io/pop-docs#2]
It would be great to have a tutorial demonstrating the new feature in the `pop up` command to run a script (`--cmd`).

It can be as simple as this example https://github.com/r0gue-io/pop-cli/pull/180#issuecomment-2124177777

**Comment by brunopgalvao** [comment]
Done:
- https://learn.onpop.io/v/appchains/guides/running-a-post-startup-command
