### ISSUE TITLE
Update: pop build contract(deprecated)

### ISSUE THREAD

**Issue by AlexD10S** [r0gue-io/pop-docs#7]
It was reported by an user in the` pop-cli`, the documentation has to be updated for `pop build contract` as it is build only with: `pop build` now.
Issue: https://github.com/r0gue-io/pop-cli/issues/268

**Comment by brunopgalvao** [comment]
<img width="795" alt="Screenshot 2024-07-29 at 12 12 25 PM" src="https://github.com/user-attachments/assets/0fd61b39-0c77-48db-88b0-a3e5cf3836de">

The blue box explicitly states this.

**Comment by brunopgalvao** [comment]
Updated.
